"""initial schema

Revision ID: 199224011762
Revises: 
Create Date: 2026-09-23 23:20:30.728377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199224011762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_type'), ['type'], unique=False)

    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('donor_name', sa.String(length=120), nullable=True),
    sa.Column('donor_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subscription_status', sa.String(length=30), nullable=True),
    sa.Column('receipt_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donations')),
    sa.UniqueConstraint('stripe_invoice_id', name=op.f('uq_donations_stripe_invoice_id'))
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_designation'), ['designation'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_stripe_session_id'), ['stripe_session_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_donations_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_start_datetime'), ['start_datetime'], unique=False)

    op.create_table('gallery_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gallery_photos'))
    )
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_photos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_photos_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_photos_is_published'), ['is_published'], unique=False)

    op.create_table('impact_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_stats'))
    )
    with op.batch_alter_table('impact_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_stats_created_at'), ['created_at'], unique=False)

    op.create_table('news_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_posts'))
    )
    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_posts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_posts_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_posts_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_posts_slug'), ['slug'], unique=True)

    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partners_type'), ['type'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('age_range', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_slug'), ['slug'], unique=True)

    op.create_table('research_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email_or_phone', sa.String(length=255), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('consent_to_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_interest'))
    )
    with op.batch_alter_table('research_interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_interest_created_at'), ['created_at'], unique=False)

    op.create_table('research_partner_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('area_of_interest', sa.String(length=300), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_partner_inquiries'))
    )
    with op.batch_alter_table('research_partner_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_partner_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_partner_inquiries_is_read'), ['is_read'], unique=False)

    op.create_table('research_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_references'))
    )
    with op.batch_alter_table('research_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_references_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_references_is_verified'), ['is_verified'], unique=False)

    op.create_table('site_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_key', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_images'))
    )
    with op.batch_alter_table('site_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_images_slot_key'), ['slot_key'], unique=True)

    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_settings_key'), ['key'], unique=True)

    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_title', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members'))
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_group'), ['group'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volunteers'))
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_created_at'), ['created_at'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=40), nullable=True),
    sa.Column('participant_first_name', sa.String(length=80), nullable=False),
    sa.Column('participant_last_name', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=False),
    sa.Column('emergency_contact_phone', sa.String(length=40), nullable=False),
    sa.Column('photo_consent', sa.Boolean(), nullable=False),
    sa.Column('guardian_consent', sa.Boolean(), nullable=True),
    sa.Column('comfort_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_registrations_program_id_programs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registrations'))
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_type'))
        batch_op.drop_index(batch_op.f('ix_registrations_status'))
        batch_op.drop_index(batch_op.f('ix_registrations_program_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_created_at'))

    op.drop_table('registrations')
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_created_at'))

    op.drop_table('volunteers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_group'))
        batch_op.drop_index(batch_op.f('ix_team_members_created_at'))

    op.drop_table('team_members')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_key'))
        batch_op.drop_index(batch_op.f('ix_site_settings_created_at'))

    op.drop_table('site_settings')
    with op.batch_alter_table('site_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_images_slot_key'))
        batch_op.drop_index(batch_op.f('ix_site_images_created_at'))

    op.drop_table('site_images')
    with op.batch_alter_table('research_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_references_is_verified'))
        batch_op.drop_index(batch_op.f('ix_research_references_created_at'))

    op.drop_table('research_references')
    with op.batch_alter_table('research_partner_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_partner_inquiries_is_read'))
        batch_op.drop_index(batch_op.f('ix_research_partner_inquiries_created_at'))

    op.drop_table('research_partner_inquiries')
    with op.batch_alter_table('research_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_interest_created_at'))

    op.drop_table('research_interest')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_slug'))
        batch_op.drop_index(batch_op.f('ix_programs_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_programs_is_active'))
        batch_op.drop_index(batch_op.f('ix_programs_division'))
        batch_op.drop_index(batch_op.f('ix_programs_created_at'))

    op.drop_table('programs')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_type'))
        batch_op.drop_index(batch_op.f('ix_partners_created_at'))

    op.drop_table('partners')
    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_posts_slug'))
        batch_op.drop_index(batch_op.f('ix_news_posts_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_posts_is_published'))
        batch_op.drop_index(batch_op.f('ix_news_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_news_posts_category'))

    op.drop_table('news_posts')
    with op.batch_alter_table('impact_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_stats_created_at'))

    op.drop_table('impact_stats')
    with op.batch_alter_table('gallery_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_photos_is_published'))
        batch_op.drop_index(batch_op.f('ix_gallery_photos_division'))
        batch_op.drop_index(batch_op.f('ix_gallery_photos_created_at'))

    op.drop_table('gallery_photos')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_datetime'))
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_events_is_published'))
        batch_op.drop_index(batch_op.f('ix_events_division'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_donations_stripe_session_id'))
        batch_op.drop_index(batch_op.f('ix_donations_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_donations_status'))
        batch_op.drop_index(batch_op.f('ix_donations_designation'))
        batch_op.drop_index(batch_op.f('ix_donations_created_at'))

    op.drop_table('donations')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_type'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_is_read'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
