"""site image stock flag and credit

Revision ID: 337cc0b223db
Revises: d201c03c972a
Create Date: 2026-09-24 01:24:32.627862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337cc0b223db'
down_revision = 'd201c03c972a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stock', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('credit', sa.String(length=300), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_images', schema=None) as batch_op:
        batch_op.drop_column('credit')
        batch_op.drop_column('is_stock')

    # ### end Alembic commands ###
