"""image alt text columns

Revision ID: 7ccf1ba26ab3
Revises: 199224011762
Create Date: 2026-09-23 23:59:43.065727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccf1ba26ab3'
down_revision = '199224011762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_alt', sa.String(length=300), nullable=True))

    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_alt', sa.String(length=300), nullable=True))

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_alt', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('image_alt')

    with op.batch_alter_table('news_posts', schema=None) as batch_op:
        batch_op.drop_column('cover_image_alt')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('image_alt')

    # ### end Alembic commands ###
