"""research reference publication

Revision ID: d201c03c972a
Revises: fecf591c8285
Create Date: 2026-09-24 01:22:56.946472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd201c03c972a'
down_revision = 'fecf591c8285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_references', schema=None) as batch_op:
        batch_op.drop_column('publication')

    # ### end Alembic commands ###
