"""curriculum modules

Revision ID: fecf591c8285
Revises: 7ccf1ba26ab3
Create Date: 2026-09-24 01:15:26.789351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecf591c8285'
down_revision = '7ccf1ba26ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('age_range', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('format_notes', sa.JSON(), nullable=False),
    sa.Column('learning_goals', sa.JSON(), nullable=False),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('adaptations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('launch_label', sa.String(length=60), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_modules'))
    )
    with op.batch_alter_table('curriculum_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_modules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_modules_division'), ['division'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_modules_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_modules_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curriculum_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_modules_status'))
        batch_op.drop_index(batch_op.f('ix_curriculum_modules_is_published'))
        batch_op.drop_index(batch_op.f('ix_curriculum_modules_division'))
        batch_op.drop_index(batch_op.f('ix_curriculum_modules_created_at'))

    op.drop_table('curriculum_modules')
    # ### end Alembic commands ###
